package model;

import interfaces.IAdminService;
import java.time.LocalDateTime;

public class Administrator extends User implements IAdminService {
    private String adminId;
    
    public Administrator(String userId, String name, String email, String phoneNumber, 
                         String password, String adminId) {
        super(userId, name, email, phoneNumber, password, "ADMIN");
        this.adminId = adminId;
    }
    
    public String getAdminId() { return adminId; }
    public void setAdminId(String adminId) { this.adminId = adminId; }
    
    @Override
    public Reservation makeReservation(ParkingSpace space, LocalDateTime start, LocalDateTime end) {
        System.out.println("🔧 Admin " + getName() + " making reservation...");
        Reservation reservation = new Reservation(null, start, end, this, space);
        reservation.setStatus(ReservationStatus.CONFIRMED); // Admin gets immediate confirmation
        return reservation;
    }
    
    @Override
    public boolean cancelReservation(Reservation reservation) {
        // Admin can cancel any reservation anytime (bypasses 30 min rule)
        if (reservation != null) {
            System.out.println("🔧 Admin override - cancelling reservation: " + reservation.getReservationId());
            reservation.setStatus(ReservationStatus.CANCELLED);
            return true;
        }
        return false;
    }
    
    // IAdminService methods
    @Override
    public void createGuestReservation() {
        System.out.println("🔧 Admin " + getName() + " created guest reservation");
    }
    
    @Override
    public void cancelAnyReservation() {
        System.out.println("🔧 Admin " + getName() + " cancelled any reservation");
    }
    
    @Override
    public void generateReport() {
        System.out.println("\n📊 SYSTEM REPORT");
        System.out.println("═══════════════════════════");
        System.out.println("Generated by: " + getName());
        System.out.println("═══════════════════════════");
    }
}